# lightgbm parameters default values

# 树的最大节点个数 Maximum tree leaves for base learners
# 说明：因为LightGBM使⽤的是leaf-wise的算法，因此在调节树的复杂程度时，使⽤的是num_leaves⽽不是max_depth。⼤致换算关系：num_leaves=2^max_depth，但是它的值的设置应该⼩于2^max_depth，否则可能会导致过拟合。
# 一棵树上的叶子节点个数。默认设置为31，和max_depth配合来空值树的形状，一般设置为(0, 2^max_depth - 1]的一个数值。是一个需要重点调节的参数，对模型性能影响很大。
num_leaves: 31
# 树的最大深度（负值代表无限制） Maximum tree depth for base learners, <=0 means no limit
# 说明：该参数用来控制过拟合。树的深度越大，则对数据的拟合程度越高，同时过拟合程度也越高，建议取值范围3-10。
max_depth: 6
# 学习速率 Boosting learning rate / eta
# 说明：为了防止过拟合，更新过程中用到的收缩步长。在每次提升计算之后，算法会直接获得新特征的权重。该参数通过缩减特征的权重使提升计算过程更加保守，建议取值范围0.01-0.2
learning_rate: 0.1
## 树模型个数 Number of boosted trees to fit
#n_estimators: 100
# 样本采样比例
# 说明：用于训练模型的子样本占整个样本集合的比例。如果设置为0.5则意味着LightGBM将随机的从整个样本集合中抽取出50%的子样本建立树模型，这能够防止过拟合
subsample: 1
# 特征选择比例
# 说明：在建立树时对特征随机采样的比例，该参数可以用来防止过拟合
colsample_bytree: 1
# 迭代次数 number of boosting iterations
# 说明：boosting迭代计算次数
num_round: 1000
